2019-07-27 06:34:36,788 ERROR: Exception on / [GET] [in /home/ayoyinka/Documents/flask/venv/lib/python3.7/site-packages/flask/app.py:1780]
Traceback (most recent call last):
  File "/home/ayoyinka/Documents/flask/venv/lib/python3.7/site-packages/flask/app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ayoyinka/Documents/flask/venv/lib/python3.7/site-packages/flask/app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ayoyinka/Documents/flask/venv/lib/python3.7/site-packages/flask/app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ayoyinka/Documents/flask/venv/lib/python3.7/site-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/home/ayoyinka/Documents/flask/venv/lib/python3.7/site-packages/flask/app.py", line 1830, in full_dispatch_request
    rv = self.preprocess_request()
  File "/home/ayoyinka/Documents/flask/venv/lib/python3.7/site-packages/flask/app.py", line 2106, in preprocess_request
    rv = func()
  File "/home/ayoyinka/Documents/flask/flasky/routes.py", line 18, in before_request
    g.search_form = SearchForm()
NameError: name 'SearchForm' is not defined
2019-07-27 06:34:40,651 ERROR: Exception on /index [GET] [in /home/ayoyinka/Documents/flask/venv/lib/python3.7/site-packages/flask/app.py:1780]
Traceback (most recent call last):
  File "/home/ayoyinka/Documents/flask/venv/lib/python3.7/site-packages/flask/app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ayoyinka/Documents/flask/venv/lib/python3.7/site-packages/flask/app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ayoyinka/Documents/flask/venv/lib/python3.7/site-packages/flask/app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ayoyinka/Documents/flask/venv/lib/python3.7/site-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/home/ayoyinka/Documents/flask/venv/lib/python3.7/site-packages/flask/app.py", line 1830, in full_dispatch_request
    rv = self.preprocess_request()
  File "/home/ayoyinka/Documents/flask/venv/lib/python3.7/site-packages/flask/app.py", line 2106, in preprocess_request
    rv = func()
  File "/home/ayoyinka/Documents/flask/flasky/routes.py", line 18, in before_request
    g.search_form = SearchForm()
NameError: name 'SearchForm' is not defined
2019-07-27 06:35:24,076 INFO: Microblog startup [in /home/ayoyinka/Documents/flask/flasky/__init__.py:55]
2019-07-27 06:35:29,381 ERROR: Exception on /index [GET] [in /home/ayoyinka/Documents/flask/venv/lib/python3.7/site-packages/flask/app.py:1780]
Traceback (most recent call last):
  File "/home/ayoyinka/Documents/flask/venv/lib/python3.7/site-packages/flask/app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ayoyinka/Documents/flask/venv/lib/python3.7/site-packages/flask/app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ayoyinka/Documents/flask/venv/lib/python3.7/site-packages/flask/app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ayoyinka/Documents/flask/venv/lib/python3.7/site-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/home/ayoyinka/Documents/flask/venv/lib/python3.7/site-packages/flask/app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ayoyinka/Documents/flask/venv/lib/python3.7/site-packages/flask/app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ayoyinka/Documents/flask/venv/lib/python3.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/ayoyinka/Documents/flask/flasky/routes.py", line 40, in index
    next_url=next_url, prev_url=prev_url) #paginate returns a pagination object and the posts can be obtained from it using items
  File "/home/ayoyinka/Documents/flask/venv/lib/python3.7/site-packages/flask/templating.py", line 135, in render_template
    context, ctx.app)
  File "/home/ayoyinka/Documents/flask/venv/lib/python3.7/site-packages/flask/templating.py", line 117, in _render
    rv = template.render(context)
  File "/home/ayoyinka/Documents/flask/venv/lib/python3.7/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/home/ayoyinka/Documents/flask/venv/lib/python3.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/ayoyinka/Documents/flask/venv/lib/python3.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ayoyinka/Documents/flask/venv/lib/python3.7/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/ayoyinka/Documents/flask/flasky/templates/index.html", line 2, in top-level template code
    {% import "bootstrap/wtf.html" as wtf %}
  File "/home/ayoyinka/Documents/flask/flasky/templates/base.html", line 1, in top-level template code
    {% extends "bootstrap/base.html" %}
  File "/home/ayoyinka/Documents/flask/venv/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 1, in top-level template code
    {% block doc -%}
  File "/home/ayoyinka/Documents/flask/venv/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 4, in block "doc"
    {%- block html %}
  File "/home/ayoyinka/Documents/flask/venv/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 20, in block "html"
    {% block body -%}
  File "/home/ayoyinka/Documents/flask/venv/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 21, in block "body"
    {% block navbar %}
  File "/home/ayoyinka/Documents/flask/flasky/templates/base.html", line 45, in block "navbar"
    <form class="navbar-form navbar-left" method="get" action="{{ url_for('search') }}">
  File "/home/ayoyinka/Documents/flask/venv/lib/python3.7/site-packages/flask/helpers.py", line 356, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/home/ayoyinka/Documents/flask/venv/lib/python3.7/site-packages/flask/app.py", line 2080, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/home/ayoyinka/Documents/flask/venv/lib/python3.7/site-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/home/ayoyinka/Documents/flask/venv/lib/python3.7/site-packages/flask/helpers.py", line 345, in url_for
    force_external=external)
  File "/home/ayoyinka/Documents/flask/venv/lib/python3.7/site-packages/werkzeug/routing.py", line 2007, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'search'. Did you mean 'user' instead?
2019-07-27 06:45:21,153 INFO: Microblog startup [in /home/ayoyinka/Documents/flask/flasky/__init__.py:55]
2019-07-27 06:53:32,915 INFO: Microblog startup [in /home/ayoyinka/Documents/flask/flasky/__init__.py:55]
